org: kynesis
app: slack-webhook-register-function
console: true
service: slack-webhook-register-service
frameworkVersion: '3'
configValidationMode: error

provider:
    name: aws
    httpApi:
        cors:
            allowedOrigins:
                - '*'
            allowedHeaders:
                - Content-Type
            allowedMethods:
                - GET
            allowCredentials: false

custom:
    serverless-offline:
        # * https://forum.serverless.com/t/possible-to-run-serverless-in-a-docker-container/5764/4
        host: 0.0.0.0

plugins:
    - serverless-offline

functions:
    slack-webhook-register-function:
        name: slack-webhook-register-function
        runtime: nodejs20.x
        handler: ./build/index.handler
        events:
            - httpApi:
                  path: /
                  method: GET
