version: '3.8'

services:
    common-functions-types:
        container_name: common-functions-types
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.common-functions-types-dev
        restart: always
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ../packages/common-functions-types/src
              target: /dashboard/packages/common-functions-types/src
            - type: bind
              source: ../packages/common-functions-types/dist
              target: /dashboard/packages/common-functions-types/dist
            - /dashboard/packages/common-functions-types/node_modules

    pixel-api-function:
        container_name: pixel-api-function
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.pixel-api-function-dev
        ports:
            - 3000:3000
        restart: always
        depends_on:
            - common-functions-types
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ../apps/pixel-api-function/src
              target: /dashboard/apps/pixel-api-function/src
            - type: bind
              source: ../packages/common-functions-types/dist
              target: /dashboard/packages/common-functions-types/dist
            - /dashboard/apps/pixel-api-function/node_modules
            - /dashboard/node_modules

    frontend:
        container_name: frontend
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.frontend-dev
        env_file:
            - ../apps/frontend/envs/.env.development
        ports:
            - 8080:8080
        restart: always
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ../apps/frontend/src
              target: /dashboard/apps/frontend/src
            - /dashboard/apps/frontend/node_modules
            - /dashboard/node_modules

networks:
    dashboard_network:
        driver: bridge
