version: '3.8'

services:
    pixel-enrichment-sqs:
        container_name: pixel-enrichment-sqs
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.pixel-enrichment-sqs-dev
        restart: always
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ../packages/pixel-enrichment-sqs/src
              target: /dashboard/packages/pixel-enrichment-sqs/src
            - type: bind
              source: ../packages/pixel-enrichment-sqs/dist
              target: /dashboard/packages/pixel-enrichment-sqs/dist
            - /dashboard/packages/pixel-enrichment-sqs/node_modules

    lambda-logger:
        container_name: lambda-logger
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.lambda-logger-dev
        restart: always
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ../packages/lambda-logger/src
              target: /dashboard/packages/lambda-logger/src
            - type: bind
              source: ../packages/lambda-logger/dist
              target: /dashboard/packages/lambda-logger/dist
            - /dashboard/packages/lambda-logger/node_modules

    slack-webhook-register-function:
        container_name: slack-webhook-register-function
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.slack-webhook-register-function-dev
        ports:
            - 3001:3001
        restart: always
        depends_on:
            - lambda-logger
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ../apps/slack-webhook-register-function/src
              target: /dashboard/apps/slack-webhook-register-function/src
            - /dashboard/apps/slack-webhook-register-function/node_modules
            - /dashboard/node_modules

networks:
    dashboard_network:
        driver: bridge
