version: '3.8'

services:
    common-functions-types:
        container_name: common-functions-types
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.common-functions-types-dev
        restart: always
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ../packages/common-functions-types/src
              target: /dashboard/packages/common-functions-types/src
            - type: bind
              source: ../packages/common-functions-types/dist
              target: /dashboard/packages/common-functions-types/dist
            - /dashboard/packages/common-functions-types/node_modules

    lambda-logger:
        container_name: lambda-logger
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.lambda-logger-dev
        restart: always
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ../packages/lambda-logger/src
              target: /dashboard/packages/lambda-logger/src
            - type: bind
              source: ../packages/lambda-logger/dist
              target: /dashboard/packages/lambda-logger/dist
            - /dashboard/packages/lambda-logger/node_modules

    pixel-api-function:
        container_name: pixel-api-function
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.pixel-api-function-dev
        ports:
            - 3000:3000
        restart: always
        depends_on:
            - common-functions-types
            - lambda-logger
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ../apps/pixel-api-function/src
              target: /dashboard/apps/pixel-api-function/src
            - type: bind
              source: ../packages/common-functions-types/dist
              target: /dashboard/packages/common-functions-types/dist
            - /dashboard/apps/pixel-api-function/node_modules
            - /dashboard/node_modules

    slack-webhook-register-function:
        container_name: slack-webhook-register-function
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.slack-webhook-register-function-dev
        ports:
            - 3001:3001
        restart: always
        depends_on:
            - lambda-logger
        networks:
            - dashboard_network
        volumes:
            - type: bind
              source: ../apps/slack-webhook-register-function/src
              target: /dashboard/apps/slack-webhook-register-function/src
            - /dashboard/apps/slack-webhook-register-function/node_modules
            - /dashboard/node_modules

networks:
    dashboard_network:
        driver: bridge
