org: kynesis
app: pixel-api-function
console: true
service: pixel-api-service
frameworkVersion: '3'
configValidationMode: error

provider:
    name: aws
    httpApi:
        cors:
            allowedOrigins:
                - '*'
            allowedHeaders:
                - Content-Type
            allowedMethods:
                - POST
            allowCredentials: false

custom:
    serverless-offline:
        # * https://forum.serverless.com/t/possible-to-run-serverless-in-a-docker-container/5764/4
        host: 0.0.0.0

plugins:
    - serverless-offline

functions:
    pixel-api-function:
        name: pixel-api-function
        runtime: nodejs20.x
        handler: ./build/index.handler
        events:
            - httpApi:
                  path: /
                  method: POST
