name: 'Chromatic'

on: push

jobs:
    chromatic:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v3
              with:
                  version: 8.15.4
                  run_install: true

            - name: Publish Web project to Chromatic
              uses: chromaui/action@latest
              with:
                  zip: true
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  workingDir: apps/frontend
