name: Destroy Terrafrom

on:
    workflow_dispatch:

jobs:
    destroy_terraform:
        name: Destroy Terraform
        runs-on: ubuntu-latest
        if: github.actor == 'kynesis-root'
        env:
            AWS_REGION: ${{ vars.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            TF_VAR_production: true
            TF_VAR_github_app_id: ${{ secrets.GH_APP_ID }}
            TF_VAR_github_app_private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
            TF_VAR_github_app_webhook_token: ${{ secrets.GH_APP_WEBHOOK_SECRET }}
            TF_VAR_proxycurl_api_key: ${{ secrets.PROXYCURL_API_KEY }}
            TF_VAR_rampedup_api_key: ${{ secrets.RAMPEDUP_API_KEY }}
            TF_VAR_coresignal_api_key: ${{ secrets.CORESIGNAL_API_KEY }}
            TF_VAR_vetric_api_key: ${{ secrets.VETRIC_API_KEY }}
            TF_VAR_aws_region: ${{ vars.AWS_REGION }}
            TF_VAR_atdata_pixel_id: ${{ secrets.ATDATA_PIXEL_ID }}
            TF_VAR_atdata_sftp_host: ${{ secrets.ATDATA_SFTP_HOST}}
            TF_VAR_atdata_sftp_port: ${{ secrets.ATDATA_SFTP_PORT}}
            TF_VAR_atdata_sftp_username: ${{ secrets.ATDATA_SFTP_USERNAME}}
            TF_VAR_atdata_sftp_password: ${{ secrets.ATDATA_SFTP_PASSWORD}}
            TF_VAR_bigbdm_client_id: ${{ secrets.BIGBDM_CLIENT_ID }}
            TF_VAR_bigbdm_client_secret: ${{ secrets.BIGBDM_CLIENT_SECRET }}
            TF_VAR_google_service_client_email: ${{ secrets.GOOGLE_SERVICE_CLIENT_EMAIL }}
            TF_VAR_google_service_private_key: ${{ secrets.GOOGLE_SERVICE_PRIVATE_KEY }}
            TF_VAR_google_sheets_spreadsheet_id: ${{ secrets.GOOGLE_SERVICE_PRIVATE_KEY }}
            TF_VAR_google_sheets_customer_domain: ${{ vars.GOOGLE_SHEETS_CUSTOMER_DOMAIN }}

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v3
              with:
                  run_install: true

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ var.AWS_REGION }}

            - name: Terraform setup
              uses: hashicorp/setup-terraform@v3

            - name: Terraform init
              working-directory: terraform
              env:
                  TERRAFORM_BACKEND_S3_BUCKET: ${{ secrets.TERRAFORM_BACKEND_S3_BUCKET }}
                  TERRAFORM_BACKEND_DYNAMODB_TABLE: ${{ secrets.TERRAFORM_BACKEND_DYNAMODB_TABLE }}
              run: |
                  terraform init \
                  -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" \
                  -backend-config="dynamodb_table=$TERRAFORM_BACKEND_DYNAMODB_TABLE" \
                  -backend-config="region=$AWS_REGION"

            - name: Terraform destroy
              working-directory: terraform
              run: terraform destroy -auto-approve
