name: Integration

on:
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    knip:
        name: Knip
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v3
              with:
                  version: 8.15.4
                  run_install: true

            - name: Run Knip
              run: pnpm knip

    inflint:
        name: Inflint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v3
              with:
                  version: 8.15.4
                  run_install: true

            - name: Run Inflint
              run: pnpm inflint

    typescript:
        name: TypeScript
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v3
              with:
                  version: 8.15.4
                  run_install: true

            - name: Run TypeScript
              run: pnpm run type-check:all

    eslint:
        name: ESLint
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v3
              with:
                  version: 8.15.4
                  run_install: true

            - name: Run ESLint
              run: pnpm lint:all

    build:
        name: Build
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v3
              with:
                  version: 8.15.4
                  run_install: true

            - name: Run build
              run: pnpm build:nested

    cspell:
        name: CSpell
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v3
              with:
                  version: 8.15.4
                  run_install: true

            - name: Run CSpell
              run: pnpm cspell

    prettier:
        name: Prettier
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'

            - uses: pnpm/action-setup@v3
              with:
                  version: 8.15.4
                  run_install: true

            - name: Run Prettier
              run: pnpm prettier
