name: Update customers domains Terrafrom

on:
    workflow_dispatch:

jobs:
    update_customers_domains_terraform:
        name: Update customers domains Terraform
        runs-on: ubuntu-latest
        if: github.actor == 'kynesis-root'
        env:
            AWS_REGION: ${{ var.AWS_REGION }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            TF_VAR_customers_domains: ${{ var.CUSTOMERS_DOMAINS }}
            TF_VAR_proxycurl_api_key: ${{ secrets.PROXYCURL_API_KEY }}
            TF_VAR_rampedup_api_key: ${{ var.RAMPEDUP_API_KEY }}
            TF_VAR_vetric_api_key: ${{ var.VETRIC_API_KEY }}
            TF_VAR_slack_client_id: ${{ secrets.SLACK_CLIENT_ID }}
            TF_VAR_slack_client_secret: ${{ secrets.SLACK_CLIENT_SECRET }}

        steps:
            - uses: actions/checkout@v4

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ var.AWS_REGION }}

            - name: Terraform setup
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_wrapper: false

            - name: Terraform init
              working-directory: terraform
              env:
                  TERRAFORM_BACKEND_S3_BUCKET: ${{ var.TERRAFORM_BACKEND_S3_BUCKET }}
                  TERRAFORM_BACKEND_DYNAMODB_TABLE: ${{ var.TERRAFORM_BACKEND_DYNAMODB_TABLE }}
              run: |
                  terraform init \
                  -backend-config="bucket=$TERRAFORM_BACKEND_S3_BUCKET" \
                  -backend-config="dynamodb_table=$TERRAFORM_BACKEND_DYNAMODB_TABLE" \
                  -backend-config="region=$AWS_REGION"

            - name: Terraform plan
              working-directory: terraform
              run: terraform plan -no-color -target=module.pixel_enrichment_api_gateway -out state.tfplan

            - name: Terraform apply
              working-directory: terraform
              run: terraform apply state.tfplan
